//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllDetails2012
    {
        public string Country { get; set; }
        public Nullable<int> VisitPercent { get; set; }
        public Nullable<int> OrderCount { get; set; }
        public Nullable<int> MemberCount { get; set; }
    }
}
