//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveDashboard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalesFiveYearsEntities : DbContext
    {
        public SalesFiveYearsEntities()
            : base("name=SalesFiveYearsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllDetails2011> AllDetails2011 { get; set; }
        public virtual DbSet<AllDetails2012> AllDetails2012 { get; set; }
        public virtual DbSet<AllDetails2013> AllDetails2013 { get; set; }
        public virtual DbSet<AllDetails2014> AllDetails2014 { get; set; }
        public virtual DbSet<AllDetails2015> AllDetails2015 { get; set; }
        public virtual DbSet<CountryGenderSales2011> CountryGenderSales2011 { get; set; }
        public virtual DbSet<CountryGenderSales2012> CountryGenderSales2012 { get; set; }
        public virtual DbSet<CountryGenderSales2013> CountryGenderSales2013 { get; set; }
        public virtual DbSet<CountryGenderSales2014> CountryGenderSales2014 { get; set; }
        public virtual DbSet<CountryGenderSales2015> CountryGenderSales2015 { get; set; }
        public virtual DbSet<CountryPercentageSales2011> CountryPercentageSales2011 { get; set; }
        public virtual DbSet<CountryPercentageSales2012> CountryPercentageSales2012 { get; set; }
        public virtual DbSet<CountryPercentageSales2013> CountryPercentageSales2013 { get; set; }
        public virtual DbSet<CountryPercentageSales2014> CountryPercentageSales2014 { get; set; }
        public virtual DbSet<CountryPercentageSales2015> CountryPercentageSales2015 { get; set; }
        public virtual DbSet<ProductCategorySales2011> ProductCategorySales2011 { get; set; }
        public virtual DbSet<ProductCategorySales2012> ProductCategorySales2012 { get; set; }
        public virtual DbSet<ProductCategorySales2013> ProductCategorySales2013 { get; set; }
        public virtual DbSet<ProductCategorySales2014> ProductCategorySales2014 { get; set; }
        public virtual DbSet<ProductCategorySales2015> ProductCategorySales2015 { get; set; }
        public virtual DbSet<SelectAllMonthsYear> SelectAllMonthsYears { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TotalYearSale> TotalYearSales { get; set; }
    }
}
