//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectAllMonthsYear
    {
        public int Id { get; set; }
        public string Months { get; set; }
        public Nullable<int> Y2011 { get; set; }
        public Nullable<int> Y2012 { get; set; }
        public Nullable<int> Y2013 { get; set; }
        public Nullable<int> Y2014 { get; set; }
        public Nullable<int> Y2015 { get; set; }
    }
}
